

from langchain_core.tools import tool
from pydantic import BaseModel, Field
from typing import List , Optional

from Agent import Agentutils

from ollama import chat
from langchain_core.prompts import PromptTemplate


class EditorInput(BaseModel) : 
    """Input For the Editor to Check the given Facts with the Output."""
    Facts : List[str] = Field(
        description="The Input Fact(s) that need to match with the Ouput."
    )
    Questions : str = Field(
        description="Summarized User Query"
    )
    GeneratedOuput : str = Field(
        description="The Ouput Generated By the LLM"
    )

class EditorResult(BaseModel) :
    isValid : bool = Field(
        description= "if the given llm ouput is related to the facts"
    )
    Reason : Optional[str] = Field(
        description="If the reason "
    )

editorFormat = PromptTemplate.from_template(
"""
- QUERY
    {Query}
- RESEARCH NOTES
    {Notes}
- DRAFT REPORT
    {Report}
"""
)


# @tool(name='Editor',args_schema=EditorInput) # Making it node so that it's easy to add conditional node
def Editor(State : Agentutils.AgentState )  : 
    """
    Checks if the Generated LLM result is Correct or not.

    Args: 
        Facts (List[str]) : The Input Fact(s) that need to match with the Ouput
        Questions (str) : Summarized User Query
        GeneratedOutput (str) : The Ouput Generated By the LLM
    
    Returns:
        EditorResult : If the Generated Ouput is correct or not And the reason if Invalid

    """
    global editorFormat
    while True :
        try :
            response = chat(
                model='EditorModel',
                messages=[
                    {
                        'role' : 'user',
                        'content' : editorFormat.format(
                            Notes = '\n\t-'.join(['']+State['research_notes']),
                            Report = State['solution'],
                            Query = State['query']
                        )
                    },
                ],
                format=EditorResult.model_json_schema(),
                think=False,
            )
            parsed_response =  EditorResult.model_validate_json(response.message.content) # This is failing sometimes [ Donno, might due to dumb llm ?]
            if parsed_response.isValid : 
                return {'Msg':State['solution'],'is_sufficient' : True}  # TODO :: Latter let's work with Reason
            
            return {'is_sufficient' : False }
        except :
            continue

